SELECT PRODUCT_CD, PROVIDER_BUSINESS_GROUP_NBR
FROM CET_RATES
WHERE
    SERVICE_CD = @servicecd
    AND SERVICE_TYPE_CD = @servicetype
    AND PLACE_OF_SERVICE_CD = @placeofservice
    AND CONTRACT_TYPE IN ('C', 'N')
